load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "src",
    deps = [
        "//src/aggregation",
        "//src/engine",
        "//src/fix",
        "//src/instrument",
        "//src/metrics",
    ],
)
